# : separates key and value
# Indentation (2 spaces, not tabs) creates nesting
# No quotes needed for simple values
# "#" for comments

# This block is meant for debuging .yaml file (Not used in the project)
debug-yaml:
  message: "I am working!!!!!!!!!"
  number: 1000

# Project configuration
