# : separates key and value
# Indentation (2 spaces, not tabs) creates nesting
# No quotes needed for simple values
# "#" for comments

# Not used in the project
quick-test:
  message: "I am working!!!!!!!!!"
  number: 10

# Project configuration
